name: Auto Version
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pipeline:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    uses: HalloftheGods/.github/.github/workflows/master.yml@main
    with:
      slug: starter-kit
